namespace Goa.Functions.ApiGateway.Payloads.V2;

/// <summary>
///     Provides detailed information about the request, including authorization, domain, and routing data.
/// </summary>
public class ProxyPayloadV2RequestContext
{
    /// <summary>
    ///     Gets or sets the AWS account ID associated with the request.
    /// </summary>
    public string? AccountId { get; set; }

    /// <summary>
    ///     Gets or sets the API Gateway API ID invoked by the request.
    /// </summary>
    public string? ApiId { get; set; }

    /// <summary>
    ///     Gets or sets the authorizer information for the request.
    ///     This contains details about the authenticated user or client making the request.
    /// </summary>
    public ProxyPayloadV2RequestAuthorizer? Authorizer { get; set; }

    /// <summary>
    ///     Gets or sets the domain name associated with the API Gateway request.
    /// </summary>
    public string? DomainName { get; set; }

    /// <summary>
    ///     Gets or sets the domain prefix used in the API Gateway request.
    /// </summary>
    public string? DomainPrefix { get; set; }

    /// <summary>
    ///     Gets or sets details of the HTTP request including method, path, and protocol information.
    /// </summary>
    public ProxyPayloadV2RequestHttpDescription? Http { get; set; }

    /// <summary>
    ///     Gets or sets the unique identifier for the request generated by API Gateway.
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    ///     Gets or sets the route ID for the matched route in the API Gateway.
    /// </summary>
    public string? RouteId { get; set; }

    /// <summary>
    ///     Gets or sets the route key for the request, which defines the route in the API Gateway that matched the request.
    /// </summary>
    public string? RouteKey { get; set; }

    /// <summary>
    ///     Gets or sets the stage of the API Gateway that processed the request.
    /// </summary>
    public string? Stage { get; set; }

    /// <summary>
    ///     Gets or sets the human-readable timestamp when the request was received.
    /// </summary>
    public string? Time { get; set; }

    /// <summary>
    ///     Gets or sets the epoch timestamp when the request was received.
    /// </summary>
    public long TimeEpoch { get; set; }

    /// <summary>
    ///     Gets or sets the authentication information for the request, which may include JWT or other tokens.
    /// </summary>
    public ProxyPayloadV2RequestAuthentication? Authentication { get; set; }
}

