namespace Goa.Functions.ApiGateway;

/// <summary>
///     Provides detailed information about the request, such as path, account ID, identity, and request metadata.
/// </summary>
public class ProxyPayloadV1RequestContext
{
    /// <summary>
    ///     Gets or sets the full path of the request.
    /// </summary>
    public string? Path { get; set; }

    /// <summary>
    ///     Gets or sets the AWS account ID associated with the request.
    /// </summary>
    public string? AccountId { get; set; }

    /// <summary>
    ///     Gets or sets the resource ID for the request.
    /// </summary>
    public string? ResourceId { get; set; }

    /// <summary>
    ///     Gets or sets the stage of the API Gateway processing the request.
    /// </summary>
    public string? Stage { get; set; }

    /// <summary>
    ///     Gets or sets the unique request ID generated by API Gateway.
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    ///     Gets or sets the identity information for the request, such as IP address and user agent.
    /// </summary>
    public ProxyPayloadV1RequestIdentity? Identity { get; set; }

    /// <summary>
    ///         Gets or sets the resource path for the request.
    /// </summary>
    public string? ResourcePath { get; set; }

    /// <summary>
    ///     Gets or sets the HTTP method (e.g., GET, POST) used in the request.
    /// </summary>
    public string? HttpMethod { get; set; }

    /// <summary>
    ///     Gets or sets the API ID associated with the API Gateway.
    /// </summary>
    public string? ApiId { get; set; }

    /// <summary>
    ///     Gets or sets the extended request ID generated by API Gateway.
    /// </summary>
    public string? ExtendedRequestId { get; set; }

    /// <summary>
    ///     Gets or sets the connection ID for WebSocket requests.
    /// </summary>
    public string? ConnectionId { get; set; }

    /// <summary>
    ///     Gets or sets the epoch timestamp when the connection was established.
    ///     Applicable for WebSocket connections.
    /// </summary>
    public long ConnectedAt { get; set; }

    /// <summary>
    ///     Gets or sets the domain name of the API Gateway.
    /// </summary>
    public string? DomainName { get; set; }

    /// <summary>
    ///     Gets or sets the domain prefix for the API Gateway request.
    /// </summary>
    public string? DomainPrefix { get; set; }

    /// <summary>
    ///     Gets or sets the event type (e.g., CONNECT, DISCONNECT) for WebSocket requests.
    /// </summary>
    public string? EventType { get; set; }

    /// <summary>
    ///     Gets or sets the message ID for WebSocket or IoT requests.
    /// </summary>
    public string? MessageId { get; set; }

    /// <summary>
    ///     Gets or sets the route key associated with the API Gateway route.
    /// </summary>
    public string? RouteKey { get; set; }

    /// <summary>
    ///     Gets or sets the authorizer context, which contains information about the authenticated user.
    /// </summary>
    public CustomAuthorizerContext? Authorizer { get; set; }

    /// <summary>
    ///     Gets or sets the operation name of the API Gateway request.
    /// </summary>
    public string? OperationName { get; set; }

    /// <summary>
    ///     Gets or sets the error message, if any, associated with the request.
    /// </summary>
    public string? Error { get; set; }

    /// <summary>
    ///     Gets or sets the latency in milliseconds between the API Gateway and the integration.
    /// </summary>
    public string? IntegrationLatency { get; set; }

    /// <summary>
    ///     Gets or sets the direction of the WebSocket message (e.g., INBOUND, OUTBOUND).
    /// </summary>
    public string? MessageDirection { get; set; }

    /// <summary>
    ///     Gets or sets the human-readable time when the request was received.
    /// </summary>
    public string? RequestTime { get; set; }

    /// <summary>
    ///     Gets or sets the epoch timestamp when the request was received.
    /// </summary>
    public long RequestTimeEpoch { get; set; }

    /// <summary>
    ///     Gets or sets the status of the API Gateway request.
    /// </summary>
    public string? Status { get; set; }
}
