name: Question
description: Ask a question about using Goa
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Goa? We're here to help!
        
        Before asking, please check:
        - [Documentation](https://github.com/im5tu/goa#readme)
        - [Existing issues](https://github.com/im5tu/goa/issues)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm trying to understand how to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to achieve
      placeholder: |
        I'm building a Lambda function that needs to...
        I've tried...
        I expected...

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, include relevant code
      render: csharp