using Goa.Clients.Dynamo.Generator.Models;

namespace Goa.Clients.Dynamo.Generator.CodeGeneration;

/// <summary>
/// Generates a static registration class for all concrete DynamoDB model types.
/// Consumers call <c>DynamoReaderRegistration.Initialize()</c> once at startup
/// to trigger the static constructor, which registers all types with DynamoItemReaderRegistry.
/// </summary>
public class ReaderRegistrationGenerator : ICodeGenerator
{
    public string GenerateCode(IEnumerable<DynamoTypeInfo> types, GenerationContext context)
    {
        var registrableTypes = types.Where(ShouldRegister).ToList();

        if (!registrableTypes.Any())
            return string.Empty;

        var typesByNamespace = registrableTypes.GroupBy(t => t.Namespace).Where(x => x.Any()).ToList();

        if (!typesByNamespace.Any())
            return string.Empty;

        // Use the first namespace as the containing namespace for the registration class
        var targetNamespace = typesByNamespace.First().Key;
        if (string.IsNullOrEmpty(targetNamespace))
            targetNamespace = "Generated";

        var builder = new CodeBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Goa.Clients.Dynamo;");
        builder.AppendLine();
        builder.AppendLine($"namespace {targetNamespace}");
        builder.OpenBrace();
        {
            builder.OpenBraceWithLine("internal static class DynamoReaderRegistration");
            {
                builder.OpenBraceWithLine("static DynamoReaderRegistration()");
                {
                    foreach (var type in registrableTypes)
                    {
                        var normalizedName = NamingHelpers.NormalizeTypeName(type.Name);
                        builder.AppendLine($"DynamoItemReaderRegistry.Register<{type.FullName}>(DynamoJsonMapper.{normalizedName}.ReadFromJson);");
                        builder.AppendLine($"DynamoItemWriterRegistry.Register<{type.FullName}>(DynamoJsonMapper.{normalizedName}.WriteToJson);");
                    }
                }
                builder.CloseBrace();
                builder.AppendLine();
                builder.AppendLine("/// <summary>");
                builder.AppendLine("/// Ensures all DynamoDB model readers are registered. Call once during application startup.");
                builder.AppendLine("/// </summary>");
                builder.AppendLine("public static void Initialize() { }");
            }
            builder.CloseBrace();
        }
        builder.CloseBrace();

        return builder.ToString();
    }

    private bool ShouldRegister(DynamoTypeInfo type)
    {
        if (type.IsAbstract)
            return false;

        return type.Attributes.Any(a => a is DynamoModelAttributeInfo) ||
               HasInheritedDynamoModel(type);
    }

    private bool HasInheritedDynamoModel(DynamoTypeInfo type)
    {
        var current = type.BaseType;
        while (current != null)
        {
            if (current.Attributes.Any(a => a is DynamoModelAttributeInfo))
                return true;

            current = current.BaseType;
        }
        return false;
    }
}
