using System.Text.Json.Serialization;
using Goa.Clients.Bedrock.Enums;
using Goa.Clients.Bedrock.Models;

namespace Goa.Clients.Bedrock.Operations.Converse;

/// <summary>
/// Response from the Bedrock Converse API.
/// </summary>
public class ConverseResponse
{
    /// <summary>
    /// The output from the model.
    /// </summary>
    [JsonPropertyName("output")]
    public ConverseOutput? Output { get; set; }

    /// <summary>
    /// The reason the model stopped generating output.
    /// </summary>
    [JsonPropertyName("stopReason")]
    public StopReason StopReason { get; set; }

    /// <summary>
    /// Token usage information.
    /// </summary>
    [JsonPropertyName("usage")]
    public TokenUsage? Usage { get; set; }

    /// <summary>
    /// Performance metrics for the request.
    /// </summary>
    [JsonPropertyName("metrics")]
    public ConverseMetrics? Metrics { get; set; }
}

/// <summary>
/// The output from a Converse API call.
/// </summary>
public class ConverseOutput
{
    /// <summary>
    /// The message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public Message? Message { get; set; }
}
